- name: install nano
  shell: yum install nano -y

- name: install pre-reqs
  become: yes
  yum:
    name: "{{ item }}"
    state: present  
  with_items:
    - curl 
    - wget 
    - policycoreutils
    - postfix
  tags: 
    - pre-reqs

- name: enable postfix
  become: yes
  service:
    name: postfix 
    enabled: yes
    state: started
  notify: restart_postfix
  tags: 
    - postfix

