- name: install yum utils
  yum:
    name: yum-utils
    state: latest
 
- name: install dev-map-pers-data
  yum:
    name: device-mapper-persistent-data
    state: latest
 
- name: install lvm2
  yum:
    name: lvm2
    state: latest
