- name: check haproxy
  package: name=haproxy state=present

- name: get haproxy version
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: set haproxy version
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: copy haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: check haproxy started and enabled
  service: name=haproxy state=started enabled=yes
