- name: copy gitLab repo
  become: yes
  template:
    src: gitlab.repo.j2
    dest: /etc/yum.repos.d/gitlab.repo
    owner: root
    group: root
    mode: 755 
  tags:
    - gitlab 
    - gitlab_repo
  notify: yum_clean

- name: install gitLab
  become: yes
  yum:
    name: gitlab-ce
    state: present
    disable_gpg_check: yes 
  tags:
    - gitlab

- name: gitlab configure
  become: yes
  shell: /bin/gitlab-ctl reconfigure
  tags: 
    - gitlab
  notify: start_gitlab

- name: open ports 
  become: yes
  firewalld: 
    permanent: true
    service: "{{ item }}"
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: display password
  debug: 
    msg: "Login credentials for the GitLab admin are  root / Passw0rd"
  tags: 
    - gitlab
