haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

#frontend
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 8888
haproxy_frontend_mode: 'http'

#backend 
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

#list backend server
haproxy_backend_servers:
   - name: app1
     address: 10.2.5.200:8888
  # - name: app2
  #   address: 192.168.0.2:80

#global vars
haproxy_global_vars: []
